
version: 2
sources:
    - name: staging
      #For bigquery:
      database:  clear-rock-338918
      # For postgres:
      #database: production
      schema: all_trips_data
      # loaded_at_field: record_loaded_at
      tables:
        - name: green_taxi_data
         # freshness:
           # error_after: {count: 6, period: hour}